<?php


/**
 * Implements hook_menu().
 */
function poet_menu() {

  $items = [];

  $items['admin/config/poet'] = [
    'title'            => 'Poet config',
    'description'      => 'This is the parent item',
    'position'         => 'left',
    'weight'           => -100,
    'page callback'    => 'system_admin_menu_block_page',
    'access arguments' => ['administer site configuration'],
    'file'             => 'system.admin.inc',
    'file path'        => drupal_get_path('module', 'system'),
  ];

  // Need at least one child item before your section will appear.
  $items['admin/config/poet/API'] = [
    'title'            => 'API settings',
    'description'      => 'Confidential API keys from Po.et',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('poet_settings_callback'),
    'access arguments' => ['administer Poet'],
    'file' => 'poet.admin.inc',
  ];

  return $items;
}

/**
 *  Implement hook_permission
 */
function poet_permission() {
  return array(
    'administer Poet' => array(
      'title' => t('Administer Poet'),
      'description' => t('Perform administration tasks for Poet.'),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter.
 **/
function poet_form_node_type_form_alter(&$form, &$form_state) {
  drupal_set_message(variable_get('poet_' . $form['#node']->type, 1));
    // Define field set in additional settings group
    $form['advanced'] = array(
      '#type' => 'fieldset',
      '#title' => t('Proof of Existence (Poet)'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#weight' => 10,
      '#group' => 'additional_settings',
    );
    // Add checkbox option
    $form['advanced']['poet'] = array(
      '#type' => 'checkbox',
      '#title' => t('Enable blockchain timestamp'),
    );
    // Set default value from automatically saved config variable
    $form['advanced']['poet']['#default_value'] = variable_get('poet_' . $form['#node']->type, 1);

}

/**
 * Implements hook_hook_info.
 **/
function poet_hook_info() {
  $hooks['poet_hook'] = array(
    'group' => 'api',
  );
  return $hooks;
}
