<?php


/**
 * Implements hook_menu().
 */
function poet_menu() {

  $items = [];

  $items['admin/config/poet'] = [
    'title'            => 'Poet config',
    'description'      => 'This is the parent item',
    'position'         => 'left',
    'weight'           => -100,
    'page callback'    => 'system_admin_menu_block_page',
    'access arguments' => ['administer site configuration'],
    'file'             => 'system.admin.inc',
    'file path'        => drupal_get_path('module', 'system'),
  ];

  // Need at least one child item before your section will appear.
  $items['admin/config/poet/API'] = [
    'title'            => 'API settings',
    'description'      => 'Confidential API keys from Po.et',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('poet_settings_callback'),
    'access arguments' => ['administer Poet'],
  ];

  return $items;
}

/**
 *  Implement hook_permission
 */
function poet_permission() {
  return array(
    'administer Poet' => array(
      'title' => t('Administer Poet'),
      'description' => t('Perform administration tasks for Poet.'),
    ),
  );
}


/**
 * Callback for the admin settings page of Po.et
 **/
function poet_settings_callback(){
  $form = array();

  $form['poet_pubkey'] = array(
    '#type' => 'textfield',
    '#title' => t('Public Key'),
    '#default_value' => variable_get('poet_pubkey',''),
    '#size' => 128,
    '#maxlength' => 128,
    '#required' => TRUE,
  );

  $form['poet_privkey'] = array(
    '#type' => 'textfield',
    '#title' => t('Private Key'),
    '#description' => t('This is Po.et private key used to sign your data. Keep it secret.'),
    '#default_value' => variable_get('poet_privkey',''),
    '#size' => 128,
    '#maxlength' => 128,
    '#required' => TRUE,
  );

  return system_settings_form($form);
}
